blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Nomoos/StoryGenerator/blob/master/docs/CHILD_ISSUES.md
    about: View detailed issue templates and documentation
  - name: 💬 Discussions
    url: https://github.com/Nomoos/StoryGenerator/discussions
    about: Ask questions and discuss ideas with the community
