name: Root Guard
on:
  push:
    branches: [ main, develop, "copilot/**" ]
  pull_request:
    branches: [ main, develop ]
jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/check-clean-root.sh
